### ISSUE TITLE
unable to pip install on python 3.5

### ISSUE THREAD

**Issue by Vuader** [vision1983/pyipcalc#1]
on OSX:

```
sudo pip-3.5 install pyipcalc
Collecting pyipcalc
  Downloading pyipcalc-0.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-295_ccf7/pyipcalc/setup.py", line 95
        print "%s %s\n" % (config['name'], version_git)
                      ^
    SyntaxError: invalid syntax```

**Comment by vision1983** [comment]
Hi Vuader, please confirm that the problem is fixed. Early commit should resolve issue.

**Comment by Vuader** [comment]
confirmed resolved:

```
sudo pip-3.5 install pyipcalc
Collecting pyipcalc
  Downloading pyipcalc-0.0.3.tar.gz
Installing collected packages: pyipcalc
  Running setup.py install for pyipcalc ... done
Successfully installed pyipcalc-0.0.3```
